import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';
import * as THREE from '../dist/vendor/three.module.min.js';import {costBuilders} from '../dist/cost-scenes.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),dist=path.join(root,'dist');
const read=p=>fs.readFileSync(path.join(dist,p),'utf8');
const data={};for(const sub of ['', 'tsmc-cost/']){const w={};w.window=w;vm.runInNewContext(read(sub+'data.js'),w);data[sub]=w;const sources=w.SOURCES||w.COST_SOURCES,companies=w.COMPANIES||w.COST_COMPANIES;assert.equal(new Set(w.TERMS.map(t=>t.id)).size,w.TERMS.length);for(const t of w.TERMS){assert(t.title&&t.body&&t.sources.length);for(const id of t.sources)assert(sources[id],`${t.id}: missing source ${id}`);for(const id of t.companies)assert(companies[id],`${t.id}: missing company ${id}`);for(const id of t.related)assert(w.TERMS.some(t=>t.id===id),`${t.id}: missing related ${id}`)}for(const [id,c]of Object.entries(companies)){assert(sources[c[4]],'missing company source '+id);assert(/^\d{4}$/.test(c[1]));}for(const s of Object.values(sources))assert.equal(new URL(s[1]).protocol,'https:');
 const html=read(sub+'index.html');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'duplicate DOM IDs');for(const m of html.matchAll(/\b(?:src|href)="([^"]+)"/g)){const u=m[1];if(u.startsWith('#')||/^https?:/.test(u))continue;assert(fs.existsSync(path.resolve(dist,sub,u)),'missing asset '+u)}console.log(`${sub||'infra/'}: ${w.TERMS.length} terms and source links valid`)}
for(const dir of [dist,path.join(dist,'tsmc-cost')])for(const f of fs.readdirSync(dir))if(f.endsWith('.js'))execFileSync(process.execPath,['--check',path.join(dir,f)],{stdio:'pipe'});
// Run the production geometry builders with real Three.js in Node, without WebGL or a browser.
const source=read('scene.js'),geometry=source.slice(source.indexOf('const palette='),source.indexOf('function setExplode'));
const fakeCanvas=()=>({width:512,height:96,getContext:()=>({fillRect(){},strokeRect(){},fillText(){}})});
for(const name of ['datacenter','rack','board','package','materials','fab','fabflow','lithography','chamber','polishing','costpackage','facility']){
 const ctx={THREE,costBuilders,scene:new THREE.Scene(),document:{createElement:fakeCanvas}};vm.createContext(ctx);vm.runInContext(geometry+'\nthis.build=()=>{const pose=builders["'+name+'"]();batchRepeatedMeshes();return {world,pickables,explodeObjects,pose}}',ctx);const result=ctx.build();assert(result.world.children.length>0);assert.equal(result.pose.length,6);assert(result.pose.every(Number.isFinite));const terms=data[['datacenter','rack','board','package','materials','fab'].includes(name)?'':'tsmc-cost/'].TERMS;for(const o of result.pickables)assert(terms.some(t=>t.id===o.userData.term),name+' unknown hit target '+o.userData.term);
 for(const v of [0,1]){for(const {obj,base,offset}of result.explodeObjects)obj.position.copy(base).addScaledVector(offset,v);result.world.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(result.world);assert([...bounds.min,...bounds.max].every(Number.isFinite),name+' invalid bounds');}
 let meshes=0;result.world.traverse(o=>{if(o.isMesh)meshes++});assert(meshes<500,name+' excessive draw objects');console.log(`${name}: geometry, hit targets and exploded bounds valid (${meshes} meshes)`);
}
// The financial simulation's actual production function, including its boundary at normal capacity.
const app=read('tsmc-cost/app.js'),fn=app.match(/function computeCosts\([^]*?\nwindow.computeCosts/)[0].replace(/\nwindow.computeCosts$/,'');const c={};vm.runInNewContext(fn+';this.calc=computeCosts',c);assert.equal(c.calc(5000,.8,30e6,1000).inventory,4000);assert.equal(c.calc(5000,.8,30e6,1000).unallocated,15e6);assert.equal(c.calc(12000,.8,30e6,1000).inventory,3500);assert.equal(c.calc(12000,.8,30e6,1000).unallocated,0);assert(c.calc(5000,.8,30e6,1000).die>c.calc(5000,.9,30e6,1000).die);console.log('Normal-capacity and yield simulation boundaries valid');
